"""add composer to tune add instrument source mutation_notation to tunesetting

Revision ID: 018b2ec32c0c
Revises: c600ea3cf22a
Create Date: 2026-06-14 14:43:00.643666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018b2ec32c0c'
down_revision: Union[str, Sequence[str], None] = 'c600ea3cf22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument', sa.Enum('flute', 'tin_whistle', 'uilleann_pipes', 'fiddle', 'concertina', 'accordion', 'banjo', 'mandolin', 'bouzouki', 'guitar', 'bodhrán', 'harp', name='instrument'), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('mutation_notation', sa.Text(), nullable=True))

    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('composer', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.drop_column('composer')

    with op.batch_alter_table('tune_settings', schema=None) as batch_op:
        batch_op.drop_column('mutation_notation')
        batch_op.drop_column('source')
        batch_op.drop_column('instrument')

    # ### end Alembic commands ###
