"""add warmup_instruments join table, drop warmup_items.instrument

Revision ID: 026536c6736a
Revises: aede90c2a665
Create Date: 2026-06-24 19:02:06.726097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '026536c6736a'
down_revision: Union[str, Sequence[str], None] = 'aede90c2a665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warmup_instruments',
    sa.Column('warmup_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Enum('flute', 'tin_whistle', 'uilleann_pipes', 'fiddle', 'concertina', 'accordion', 'banjo', 'mandolin', 'bouzouki', 'guitar', 'bodhrán', 'harp', name='instrument'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['warmup_id'], ['warmup_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('warmup_id', 'instrument')
    )
    # Migrate existing single-instrument rows into the join table.
    op.execute(
        "INSERT INTO warmup_instruments (warmup_id, instrument, created_at, updated_at) "
        "SELECT id, instrument, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP "
        "FROM warmup_items WHERE instrument IS NOT NULL"
    )
    with op.batch_alter_table('warmup_items', schema=None) as batch_op:
        batch_op.drop_column('instrument')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warmup_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument', sa.VARCHAR(length=14), nullable=True))

    op.drop_table('warmup_instruments')
    # ### end Alembic commands ###
