"""add display_alias_id to box and list entries

Revision ID: 14bdceb5cccf
Revises: 3e71efc09f16
Create Date: 2026-07-09 20:00:12.642455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14bdceb5cccf'
down_revision: Union[str, Sequence[str], None] = '3e71efc09f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_box_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_alias_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tune_box_entries_display_alias_id', 'tune_aliases', ['display_alias_id'], ['id'])

    with op.batch_alter_table('tune_list_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_alias_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tune_list_entries_display_alias_id', 'tune_aliases', ['display_alias_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_list_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tune_list_entries_display_alias_id', type_='foreignkey')
        batch_op.drop_column('display_alias_id')

    with op.batch_alter_table('tune_box_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tune_box_entries_display_alias_id', type_='foreignkey')
        batch_op.drop_column('display_alias_id')

    # ### end Alembic commands ###
