"""add tune list set entries and difficulties

Revision ID: 16937de1282b
Revises: a3aae1c995de
Create Date: 2026-07-13 21:22:44.987321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16937de1282b'
down_revision: Union[str, Sequence[str], None] = 'a3aae1c995de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tune_list_set_difficulties',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='ck_tune_list_set_difficulty_range'),
    sa.ForeignKeyConstraint(['list_id'], ['practice_lists.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['tune_sets.id'], ),
    sa.PrimaryKeyConstraint('list_id', 'set_id')
    )
    op.create_table('tune_list_set_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['practice_lists.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['tune_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'set_id', name='uq_tune_list_set_entry_list_set')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tune_list_set_entries')
    op.drop_table('tune_list_set_difficulties')
    # ### end Alembic commands ###
