"""add tune_boxes tune_box_instruments tune_box_entries; add fk to student_progress box_id

Revision ID: 1fd3a070b4f4
Revises: bc0fc2a823a6
Create Date: 2026-06-17 04:55:01.301984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd3a070b4f4'
down_revision: Union[str, Sequence[str], None] = 'bc0fc2a823a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tune_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tune_box_instruments',
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Enum('flute', 'tin_whistle', 'uilleann_pipes', 'fiddle', 'concertina', 'accordion', 'banjo', 'mandolin', 'bouzouki', 'guitar', 'bodhrán', 'harp', name='instrument'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['tune_boxes.id'], ),
    sa.PrimaryKeyConstraint('box_id', 'instrument')
    )
    op.create_table('tune_box_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['tune_boxes.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['tune_settings.id'], ),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('box_id', 'tune_id', name='uq_tune_box_entry_box_tune')
    )
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_student_progress_box_id', 'tune_boxes', ['box_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_constraint('fk_student_progress_box_id', type_='foreignkey')

    op.drop_table('tune_box_entries')
    op.drop_table('tune_box_instruments')
    op.drop_table('tune_boxes')
    # ### end Alembic commands ###
