"""add sort_name to tune_aliases

Revision ID: 315e213ce8b4
Revises: cfb6802ba92e
Create Date: 2026-06-17 08:56:10.889936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '315e213ce8b4'
down_revision: Union[str, Sequence[str], None] = 'cfb6802ba92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_aliases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_name', sa.String(length=200), nullable=False, server_default=''))
        batch_op.create_index(batch_op.f('ix_tune_aliases_sort_name'), ['sort_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tune_aliases_sort_name'))
        batch_op.drop_column('sort_name')

    # ### end Alembic commands ###
