"""add practice_lists and tune_list_entries

Revision ID: 3591995e8069
Revises: 315e213ce8b4
Create Date: 2026-06-17 17:16:15.867909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3591995e8069'
down_revision: Union[str, Sequence[str], None] = '315e213ce8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('list_type', sa.Enum('repertoire', 'woodshed', name='practicelisttype'), nullable=False),
    sa.Column('progress_goal', sa.Enum('just_learning', 'getting_there', 'nearly_there', 'session_ready', 'committed', 'performance_ready', 'solo_ready', name='progressstatus'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['tune_boxes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tune_list_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['practice_lists.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['tune_settings.id'], ),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tune_id', 'list_id', name='uq_tune_list_entry_tune_list')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tune_list_entries')
    op.drop_table('practice_lists')
    # ### end Alembic commands ###
