"""add thesession attribution fields to tune and tunesetting

Revision ID: 3e71efc09f16
Revises: 77fca5923bef
Create Date: 2026-07-06 15:32:22.983442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e71efc09f16'
down_revision: Union[str, Sequence[str], None] = '77fca5923bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesession_setting_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thesession_username', sa.String(length=200), nullable=True))

    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thesession_tune_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('thesession_username', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.drop_column('thesession_username')
        batch_op.drop_column('thesession_tune_id')

    with op.batch_alter_table('tune_settings', schema=None) as batch_op:
        batch_op.drop_column('thesession_username')
        batch_op.drop_column('thesession_setting_id')

    # ### end Alembic commands ###
