"""add tuneset source abc_header member setting_id tunebox_set_entry tuneset_tempo

Revision ID: 522b930c4681
Revises: 661611a1540d
Create Date: 2026-06-26 07:24:53.718204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522b930c4681'
down_revision: Union[str, Sequence[str], None] = '661611a1540d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tune_box_set_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['tune_boxes.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['tune_sets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('box_id', 'set_id', name='uq_tune_box_set_entry_box_set')
    )
    op.create_table('tune_set_tempos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('tempo', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['tune_boxes.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['tune_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'box_id', 'set_id')
    )
    with op.batch_alter_table('tune_set_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setting_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tune_set_members_setting_id', 'tune_settings', ['setting_id'], ['id'])

    with op.batch_alter_table('tune_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('abc_header', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_sets', schema=None) as batch_op:
        batch_op.drop_column('abc_header')
        batch_op.drop_column('source')

    with op.batch_alter_table('tune_set_members', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tune_set_members_setting_id', type_='foreignkey')
        batch_op.drop_column('setting_id')

    op.drop_table('tune_set_tempos')
    op.drop_table('tune_box_set_entries')
    # ### end Alembic commands ###
