"""add instrument_tunings table

Revision ID: 638eed9e42d1
Revises: d4423e6066e0
Create Date: 2026-07-17 20:35:39.239317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '638eed9e42d1'
down_revision: Union[str, Sequence[str], None] = 'd4423e6066e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_tunings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Enum('flute', 'tin_whistle', 'uilleann_pipes', 'fiddle', 'concertina', 'accordion', 'banjo', 'mandolin', 'bouzouki', 'guitar', 'bodhrán', 'harp', name='instrument'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('strings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'instrument', 'name', name='uq_instrument_tuning_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_tunings')
    # ### end Alembic commands ###
