"""add thesession community data side tables

Revision ID: 68ab98a8b2d0
Revises: 638eed9e42d1
Create Date: 2026-07-18 14:57:51.769501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ab98a8b2d0'
down_revision: Union[str, Sequence[str], None] = '638eed9e42d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesession_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('town', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesession_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('recording_name', sa.String(length=200), nullable=False),
    sa.Column('track_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tune_name', sa.String(length=200), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesession_recordings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesession_recordings_recording_id'), ['recording_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesession_recordings_tune_id'), ['tune_id'], unique=False)

    op.create_table('thesession_sets',
    sa.Column('tuneset_id', sa.Integer(), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tuneset_id')
    )
    op.create_table('thesession_venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('town', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thesession_set_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tuneset_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tuneset_id'], ['thesession_sets.tuneset_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesession_set_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesession_set_members_tune_id'), ['tune_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesession_set_members_tuneset_id'), ['tuneset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesession_set_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesession_set_members_tuneset_id'))
        batch_op.drop_index(batch_op.f('ix_thesession_set_members_tune_id'))

    op.drop_table('thesession_set_members')
    op.drop_table('thesession_venues')
    op.drop_table('thesession_sets')
    with op.batch_alter_table('thesession_recordings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesession_recordings_tune_id'))
        batch_op.drop_index(batch_op.f('ix_thesession_recordings_recording_id'))

    op.drop_table('thesession_recordings')
    op.drop_table('thesession_events')
    # ### end Alembic commands ###
