"""add tuneset tunesetmember

Revision ID: 698cb50a4bc7
Revises: 46e25adf2363
Create Date: 2026-06-14 07:29:32.863447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '698cb50a4bc7'
down_revision: Union[str, Sequence[str], None] = '46e25adf2363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tune_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('flow_difficulty', sa.Integer(), nullable=True),
    sa.Column('flow_difficulty_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('flow_difficulty IS NULL OR (flow_difficulty >= 1 AND flow_difficulty <= 5)', name='ck_tuneset_flow_difficulty_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tune_set_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['tune_sets.id'], ),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tune_set_members')
    op.drop_table('tune_sets')
    # ### end Alembic commands ###
