"""add thesession tune reference side tables

Revision ID: 77fca5923bef
Revises: 7c09e4bd6838
Create Date: 2026-07-06 13:17:57.318220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77fca5923bef'
down_revision: Union[str, Sequence[str], None] = '7c09e4bd6838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thesession_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=200), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesession_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesession_aliases_tune_id'), ['tune_id'], unique=False)

    op.create_table('thesession_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tune_type_raw', sa.String(length=50), nullable=False),
    sa.Column('meter', sa.String(length=20), nullable=False),
    sa.Column('mode_raw', sa.String(length=50), nullable=False),
    sa.Column('abc', sa.Text(), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('composer', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesession_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesession_settings_setting_id'), ['setting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_thesession_settings_tune_id'), ['tune_id'], unique=False)

    op.create_table('thesession_tune_popularity',
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tunebooks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('tune_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesession_tune_popularity')
    with op.batch_alter_table('thesession_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesession_settings_tune_id'))
        batch_op.drop_index(batch_op.f('ix_thesession_settings_setting_id'))

    op.drop_table('thesession_settings')
    with op.batch_alter_table('thesession_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesession_aliases_tune_id'))

    op.drop_table('thesession_aliases')
    # ### end Alembic commands ###
