"""add transpose key and octave to box and list entries

Revision ID: 7ae690dc49a9
Revises: 14bdceb5cccf
Create Date: 2026-07-11 05:23:54.012948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae690dc49a9'
down_revision: Union[str, Sequence[str], None] = '14bdceb5cccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_box_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transpose_key_root', sa.Enum('C', 'C_sharp', 'D_flat', 'D', 'E_flat', 'E', 'F', 'F_sharp', 'G_flat', 'G', 'A_flat', 'A', 'B_flat', 'B', name='keyroot'), nullable=True))
        batch_op.add_column(sa.Column('transpose_octave', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('tune_list_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transpose_key_root', sa.Enum('C', 'C_sharp', 'D_flat', 'D', 'E_flat', 'E', 'F', 'F_sharp', 'G_flat', 'G', 'A_flat', 'A', 'B_flat', 'B', name='keyroot'), nullable=True))
        batch_op.add_column(sa.Column('transpose_octave', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_list_entries', schema=None) as batch_op:
        batch_op.drop_column('transpose_octave')
        batch_op.drop_column('transpose_key_root')

    with op.batch_alter_table('tune_box_entries', schema=None) as batch_op:
        batch_op.drop_column('transpose_octave')
        batch_op.drop_column('transpose_key_root')

    # ### end Alembic commands ###
