"""add setting_progress

Revision ID: 8635670189e0
Revises: 3591995e8069
Create Date: 2026-06-17 18:36:42.492861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8635670189e0'
down_revision: Union[str, Sequence[str], None] = '3591995e8069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('setting_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('just_learning', 'getting_there', 'nearly_there', 'session_ready', 'committed', 'performance_ready', 'solo_ready', name='progressstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['box_id'], ['tune_boxes.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['tune_settings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'setting_id', 'box_id', name='uq_setting_progress_user_setting_box')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting_progress')
    # ### end Alembic commands ###
