"""add tune box set difficulties

Revision ID: a3aae1c995de
Revises: 7ae690dc49a9
Create Date: 2026-07-13 20:02:07.402910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3aae1c995de'
down_revision: Union[str, Sequence[str], None] = '7ae690dc49a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tune_box_set_difficulties',
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='ck_tune_box_set_difficulty_range'),
    sa.ForeignKeyConstraint(['box_id'], ['tune_boxes.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['tune_sets.id'], ),
    sa.PrimaryKeyConstraint('box_id', 'set_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tune_box_set_difficulties')
    # ### end Alembic commands ###
