"""add box_id to practice_sessions

Revision ID: a45b1717dd6d
Revises: 1e410e1aafc6
Create Date: 2026-06-20 15:27:32.620398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a45b1717dd6d'
down_revision: Union[str, Sequence[str], None] = '1e410e1aafc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'tune_boxes', ['box_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_sessions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('box_id')

    # ### end Alembic commands ###
