"""add actual_minutes to practice_session_items

Revision ID: aede90c2a665
Revises: a45b1717dd6d
Create Date: 2026-06-20 20:32:03.155981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aede90c2a665'
down_revision: Union[str, Sequence[str], None] = 'a45b1717dd6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_session_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_minutes', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_session_items', schema=None) as batch_op:
        batch_op.drop_column('actual_minutes')

    # ### end Alembic commands ###
