"""add tune tunesetting tunedifficulty

Revision ID: b8ee69b0bb2c
Revises: c7db103d3a05
Create Date: 2026-06-14 06:19:39.403956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8ee69b0bb2c'
down_revision: Union[str, Sequence[str], None] = 'c7db103d3a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tunes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('tune_type', sa.Enum('reel', 'jig', 'slip_jig', 'hornpipe', 'polka', 'slide', 'strathspey', 'waltz', 'air', 'march', 'barndance', name='tunetype'), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('time_signature', sa.String(length=10), nullable=False),
    sa.Column('origin', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tune_difficulties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.Enum('flute', 'tin_whistle', 'uilleann_pipes', 'fiddle', 'concertina', 'accordion', 'banjo', 'mandolin', 'bouzouki', 'guitar', 'bodhrán', 'harp', name='instrument'), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('difficulty >= 1 AND difficulty <= 5', name='ck_tune_difficulty_range'),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tune_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('abc_notation', sa.Text(), nullable=False),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('ornamentation_level', sa.Enum('none', 'minimal', 'moderate', 'full', name='ornamentationlevel'), nullable=False),
    sa.Column('source_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tune_settings')
    op.drop_table('tune_difficulties')
    op.drop_table('tunes')
    # ### end Alembic commands ###
