"""add box_id to student_progress

Revision ID: bc0fc2a823a6
Revises: 50c587226471
Create Date: 2026-06-17 04:16:24.243822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0fc2a823a6'
down_revision: Union[str, Sequence[str], None] = '50c587226471'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_student_progress_user_tune_box', ['user_id', 'tune_id', 'box_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_progress', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_progress_user_tune_box', type_='unique')
        batch_op.drop_column('box_id')

    # ### end Alembic commands ###
