"""split key into key_root and key_mode

Revision ID: c600ea3cf22a
Revises: 6c34bdedcad9
Create Date: 2026-06-14 13:47:21.670901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c600ea3cf22a'
down_revision: Union[str, Sequence[str], None] = '6c34bdedcad9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_root', sa.Enum('C', 'C_sharp', 'D_flat', 'D', 'E_flat', 'E', 'F', 'F_sharp', 'G_flat', 'G', 'A_flat', 'A', 'B_flat', 'B', name='keyroot'), nullable=False))
        batch_op.add_column(sa.Column('key_mode', sa.Enum('major', 'minor', 'dorian', 'mixolydian', 'lydian', name='keymode'), nullable=False))
        batch_op.drop_column('key')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('key_mode')
        batch_op.drop_column('key_root')

    # ### end Alembic commands ###
