"""add focus flag, review session item type, session prefs

Revision ID: ce3830ada50c
Revises: 10d144490ed6
Create Date: 2026-07-20 18:20:58.665131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3830ada50c'
down_revision: Union[str, Sequence[str], None] = '10d144490ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('learning_tune_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_tune_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retention_tune_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('warmup_pct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_pct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('learning_pct', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('retention_pct', sa.Integer(), nullable=True))

    with op.batch_alter_table('tune_list_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_focus', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('focus_goal_reached_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tune_list_entries', schema=None) as batch_op:
        batch_op.drop_column('focus_goal_reached_at')
        batch_op.drop_column('is_focus')

    with op.batch_alter_table('practice_lists', schema=None) as batch_op:
        batch_op.drop_column('retention_pct')
        batch_op.drop_column('learning_pct')
        batch_op.drop_column('review_pct')
        batch_op.drop_column('warmup_pct')
        batch_op.drop_column('retention_tune_count')
        batch_op.drop_column('review_tune_count')
        batch_op.drop_column('learning_tune_count')

    # ### end Alembic commands ###
