"""add auth schema: google_sub, content visibility, enrollment, share link

Revision ID: d4423e6066e0
Revises: 16937de1282b
Create Date: 2026-07-14 20:20:59.119575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4423e6066e0'
down_revision: Union[str, Sequence[str], None] = '16937de1282b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', name='enrollmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'student_id', name='uq_enrollment_teacher_student')
    )
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=True),
    sa.Column('setting_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(tune_id IS NOT NULL AND setting_id IS NULL) OR (tune_id IS NULL AND setting_id IS NOT NULL)', name='ck_share_link_exactly_one_target'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['setting_id'], ['tune_settings.id'], ),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_share_links_token'), ['token'], unique=True)

    with op.batch_alter_table('tune_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Enum('public', 'enrolled', 'private', name='contentvisibility'), server_default='public', nullable=False))

    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.Enum('public', 'enrolled', 'private', name='contentvisibility'), server_default='public', nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)
        batch_op.drop_column('hashed_password')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_column('google_sub')

    with op.batch_alter_table('tunes', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    with op.batch_alter_table('tune_settings', schema=None) as batch_op:
        batch_op.drop_column('visibility')

    with op.batch_alter_table('share_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_share_links_token'))

    op.drop_table('share_links')
    op.drop_table('enrollments')
    # ### end Alembic commands ###
