"""add studentprogress

Revision ID: e5fe1aa4e3f0
Revises: 97aff3afdc1c
Create Date: 2026-06-14 08:18:39.714465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5fe1aa4e3f0'
down_revision: Union[str, Sequence[str], None] = '97aff3afdc1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tune_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('just_learning', 'getting_there', 'nearly_there', 'session_ready', 'committed', 'performance_ready', 'solo_ready', name='progressstatus'), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Float(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('last_practiced', sa.DateTime(), nullable=True),
    sa.Column('next_suggested', sa.DateTime(), nullable=True),
    sa.Column('teacher_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('confidence >= 1 AND confidence <= 5', name='ck_student_progress_confidence_range'),
    sa.ForeignKeyConstraint(['tune_id'], ['tunes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_progress')
    # ### end Alembic commands ###
